pumukitadmin_mms_index:
    pattern: /series/{id}
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.mms:indexAction
        _sylius:
            filterable: true

pumukitadmin_mms_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:createAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_update:
    pattern: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:updateAction

pumukitadmin_mms_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.mms:batchDeleteAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.mms:deleteAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.mms:copyAction
        _sylius:
            redirect: pumukitadmin_mms_index

pumukitadmin_mms_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.mms:showAction