language: php
sudo: required

php:
  - 5.4
  - 5.5

env:
  - PUMUKIT2_OPENCAST_HOST="http://engage14.campusdomar.es" PUMUKIT2_OPENCAST_USERNAME="" PUMUKIT2_OPENCAST_PASSWORD="" PUMUKIT2_OPENCAST_PLAYER="/paellaengage/ui/cmarwatch.html" MONGO_VERSION=stable

matrix:
  include:
    - php: 5.3
      env: MONGO_VERSION=1.2.12
    - php: 5.3
      env: MONGO_VERSION=1.3.7
    - php: 5.3
      env: MONGO_VERSION=1.4.5

services:
  - mongodb

before_script: 
  - /home/travis/.phpenv/versions/5.3.3/bin/composer self-update
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - mongo --version
  - echo 'date.timezone = "Europe/Madrid"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export TZ="Europe/Madrid"
  - php -i|grep mongo
  - sleep 5
  - if [ -f "~/satis/bin/satis" ]; then ~/satis/bin/satis --no-interaction build ~/packages.json ~/packages; fi
  - if [ -f "app/config/parameters.yml" ]; then rm app/config/parameters.yml; fi
  - if [ -d "app/cache" ]; then rm -Rf app/cache/*; fi
  - if [ -d "app/logs" ]; then rm -Rf app/logs/*; fi
  - mkdir -p build
  - php ~/.phpenv/versions/5.3.3/bin/composer
  - php composer.phar install --no-interaction
  - php app/check.php
  - sudo php app/console doctrine:mongodb:schema:create 
  - php app/console cache:clear
  - php app/console pumukit:init:repo all --force

script: sudo php bin/phpunit --log-junit build/unit.xml  --coverage-html build/coverage --coverage-clover build/coverage/coverage.xml -c app
