sudo: false
language: php

addons:
  apt:
    packages:
      - mediainfo
    

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=stable

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - php -i
  - composer install


script:
    - phpunit -c app


