sudo: required
dist: trusty
language: php

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=stable

services:
  - mongodb

before_script:
  - composer install --dev
  - mongo --version
  - php -i


script:
    - phpunit -c app


