sudo: false
language: php

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=stable

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server

before_script:
  - composer self-update
  - mongo --version
  - php -i
  - composer install


script:
    - phpunit -c app


