imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: @PumukitAdminBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# MongoDB configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: "%mongodb_database%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Pumukit\SchemaBundle\Document\User

# Pumukit2 parameters
parameters:
    pumukit2.locales:
        - es
        - en

pumukit_encoder:
    cpus: 
        local:
            host: 127.0.0.1
    profiles:
        master_copy:
            display: false
            wizard: true
            master: true
            resolution_hor: 0
            resolution_ver: 0
            framerate: 0
            channels: 1
            audio: false
            bat: 'cp "{{input}}" "{{output}}"'
            streamserver:
                name: Localmaster
                type: store
                host: 127.0.0.1
                description: Local master server
                dir_out: '/mnt/nas/storage/masters'
            app: cp
            rel_duration_size: 1
            rel_duration_trans: 1
        master_video_h264:
            display: false
            wizard: true
            master: true
            format: mp4
            codec: h264
            mime_type: 'video/x-mp4'
            extension: mp4
            resolution_hor: 0
            resolution_ver: 0
            bitrate: 1 Mbps
            framerate: 25
            channels: 1
            audio: false
            bat: |
                'BitRate=$(/usr/local/bin/ffprobe "{{input}}" -v 0 -show_format -print_format default=nk=1:nw=1 | sed -n 9p)
                [[ "$(( BitRate ))" -gt 6000000 ]] && : $(( BitRate = 6000000 ))
                FrameRate=$(/usr/local/bin/ffprobe "{{input}}" -v 0 -show_streams -select_streams v -print_format default=nk=1:nw=1 | sed -n 18p) 
                BufSize=$(( BitRate*20/FrameRate ))
                AudioSampleRate=$(/usr/local/bin/ffprobe "{{input}}" -v 0 -show_streams -select_streams a -print_format default=nk=1:nw=1 |sed -n 10p)
                AudioBitRate=$(/usr/local/bin/ffprobe "{{input}}" -v 0 -show_streams -select_streams a -print_format default=nk=1:nw=1 |sed -n 22p)
                width=$(/usr/local/bin/ffprobe "{{input}}" -v 0 -show_streams -select_streams v  -print_format default=nk=1:nw=1 |sed -n 9p)
                [[ "$(( width %% 2 ))" -ne 0 ]] && : $(( width += 1 ))
                height=$(/usr/local/bin/ffprobe "{{input}}" -v 0 -show_streams -select_streams v  -print_format default=nk=1:nw=1 |sed -n 10p)
                [[ "$(( height %% 2 ))" -ne 0 ]] && : $(( height += 1 )) 
                /usr/local/bin/ffmpeg -y -i "{{input}}" -acodec libfdk_aac -b:a $AudioBitRate -ac 2 -ar $AudioSampleRate -vcodec libx264 -r 25 -preset slow -crf 15 -maxrate $BitRate -bufsize $BufSize -s $width"x"$height -threads 0 "{{output}}"'
            streamserver:
                name: Localmaster
                type: store
                host: 127.0.0.1
                description: Local master server
                dir_out: '/mnt/nas/storage/masters'
            app: ffmpeg
            rel_duration_size: 1
            rel_duration_trans: 1
