imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        encoder:
            type:         fingers_crossed
            action_level: error
            handler:      encoder_nested
            channels:     [encoder]
        encoder_nested:
            type:   stream
            path:   "%kernel.logs_dir%/encoder_%kernel.environment%.log"
            level:  debug
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            excluded_404s: [.]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
