pumukit_transco_api_cpus:
    type: rest
    resource: Pumukit\TranscoBundle\Controller\CpuController
    prefix:   /admin/transco/api/

pumukit_schema:
    resource: "@PumukitSchemaBundle/Controller/"
    type:     annotation
    prefix:   /schema/

pumukit_crud:
    resource: "@PumukitCRUDBundle/Controller/"
    type:     annotation
    prefix:   /admin/crud/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /admin/api/doc