pumukit_transco_api_cpus:
    type: rest
    resource: Pumukit\TranscoBundle\Controller\CpuAPIController
    prefix:   /admin/transco/api/
    
pumukit_transco_cpus:
    resource: "@PumukitTranscoBundle/Controller/"
    type:     annotation
    prefix:   /admin/transco/

pumukit_schema:
    resource: "@PumukitSchemaBundle/Controller/"
    type:     annotation
    prefix:   /schema/

pumukit_crud:
    resource: "@PumukitCRUDBundle/Controller/"
    type:     annotation
    prefix:   /admin/crud/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /admin/api/doc