pumukit_transco:
    resource: "@PumukitTranscoBundle/Controller/"
    type:     annotation
    prefix:   /admin/transco
    
pumukit_transco_api_cpus:
    type: rest
    resource: Pumukit\TranscoBundle\Controller\CpusController
    prefix:   /admin/transco/api/

pumukit_schema:
    resource: "@PumukitSchemaBundle/Controller/"
    type:     annotation
    prefix:   /schema/

pumukit_crud:
    resource: "@PumukitCRUDBundle/Controller/"
    type:     annotation
    prefix:   /admin/crud/
