pumukitnewadmin_broadcast_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_broadcast_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:createAction
        _sylius:
            redirect: pumukitnewadmin_broadcast_index

pumukitnewadmin_broadcast_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:updateAction
        _sylius:
            redirect: pumukitnewadmin_broadcast_index

pumukitnewadmin_broadcast_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_broadcast_index

pumukitnewadmin_broadcast_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:deleteAction
        _sylius:
            redirect: pumukitnewadmin_broadcast_index

pumukitnewadmin_broadcast_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:copyAction
        _sylius:
            redirect: pumukitnewadmin_broadcast_index

pumukitnewadmin_broadcast_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:showAction

pumukitnewadmin_broadcast_default:
    pattern: /{id}/default
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:defaultAction
        _sylius:
            redirect: pumukitnewadmin_broadcast_index

pumukitnewadmin_broadcast_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.broadcast:listAction