pumukitnewadmin_group_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Group:index
        _sylius:
            filterable: true

pumukitnewadmin_group_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Group:create
        _sylius:
            redirect: pumukitnewadmin_group_index

pumukitnewadmin_group_update:
    path: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Group:update
        _sylius:
            redirect: pumukitnewadmin_group_index

pumukitnewadmin_group_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:batchDelete
        _sylius:
            redirect: pumukitnewadmin_group_index

pumukitnewadmin_group_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:delete
        _sylius:
            redirect: pumukitnewadmin_group_index

pumukitnewadmin_group_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Group:list
        _sylius:
            filterable: true

pumukitnewadmin_group_info:
    path: /{id}/info
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Group:info

pumukitnewadmin_group_data_resources:
    path: /{id}/dataresources
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Group:dataResources

pumukitnewadmin_group_delete_user:
    path: /{id}/deleteuser/{userId}
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:deleteUser

pumukitnewadmin_group_delete_multimediaobject:
    path: /{id}/deletemultimediaobject/{mmId}
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:deleteMultimediaObject

pumukitnewadmin_group_delete_embeddedbroadcast:
    path: /{id}/deleteembeddedbroadcast/{mmId}
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:deleteEmbeddedBroadcast

pumukitnewadmin_group_can_be_deleted:
    path: /{id}/canbedeleted
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Group:canBeDeleted

pumukitnewadmin_group_delete_all_users:
    path: /{id}/deleteallusers
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:deleteAllUsers

pumukitnewadmin_group_delete_all_multimediaobjects:
    path: /{id}/deleteallmultimediaobjects
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:deleteAllMultimediaObjects

pumukitnewadmin_group_delete_all_embeddedbroadcasts:
    path: /{id}/deleteallembeddedbroadcasts
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Group:deleteAllEmbeddedBroadcasts