pumukitnewadmin_eventpic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEventPic:create

pumukitnewadmin_eventpic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEventPic:update

pumukitnewadmin_eventpic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEventPic:upload

pumukitnewadmin_eventpic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEventPic:delete
