pumukitnewadmin_mmspic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:index
        _sylius:
            filterable: true

pumukitnewadmin_mmspic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:create
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mmspic_generate:
    path: /generate/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:generate

pumukitnewadmin_mmspic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:update

pumukitnewadmin_mmspic_batch_delete:
    path: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:batchDelete
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mmspic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:delete


pumukitnewadmin_mmspic_up:
    path: /{id}/up
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:up


pumukitnewadmin_mmspic_down:
    path: /{id}/down
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:down


pumukitnewadmin_mmspic_list:
    path: /{id}/list
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:list


pumukitnewadmin_mmspic_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:show


pumukitnewadmin_mmspic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:upload

pumukitnewadmin_mmspic_picstoaddlist:
    path: /{id}/picstoaddlist
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:MultimediaObjectPic:picstoaddlist
