pumukitnewadmin_playlist_index:
    path: /
    methods: [GET]
    defaults:

        _controller: PumukitNewAdminBundle:Playlist:index
        _sylius:
            filterable: true

pumukitnewadmin_playlist_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:search

pumukitnewadmin_playlist_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:create
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlist_update:
    path: /{id}/update
    methods: [GET, POST, DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:update

pumukitnewadmin_playlist_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:batchDelete
        _sylius:
            redirect: pumukitnewadmin_playlist_list

pumukitnewadmin_playlist_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:delete
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlist_generate_magic_url:
    path: /{id}/generatemagic
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:generateMagicUrl

pumukitnewadmin_playlist_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:copy
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlist_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:list

pumukitnewadmin_playlist_invert_announce:
    path: /invertannounce
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:invertAnnounce

pumukitnewadmin_playlist_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Playlist:show
