pumukitnewadmin_playlistmms_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_playlistmms_create:
    pattern: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:createAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_batch_delete:
    pattern: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:deleteAction

pumukitnewadmin_playlistmms_show:
    pattern: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:showAction

pumukitnewadmin_playlistmms_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:upAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:downAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:topAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:bottomAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:listAction

pumukitnewadmin_playlistmms_cut:
    pattern: /cut
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:cutAction

pumukitnewadmin_playlistmms_paste:
    pattern: /paste
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:pasteAction

pumukitnewadmin_playlistmms_reorder:
    pattern: /reorder
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:reorderAction

pumukitnewadmin_playlistmms_modal:
    pattern: /modal
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:addMmobjModalAction

pumukitnewadmin_playlistmms_search_modal:
    pattern: /modal_search
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:searchMmobjsModalAction

pumukitnewadmin_playlistmms_url_modal:
    pattern: /modal_url
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.playlistmms:urlMmobjModalAction