pumukitnewadmin_playlistpic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:index
        _sylius:
            filterable: true

pumukitnewadmin_playlistpic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:create
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlistpic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:update

pumukitnewadmin_playlistpic_batch_delete:
    path: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:batchDelete
        _sylius:
            redirect: pumukitnewadmin_playlist_index

pumukitnewadmin_playlistpic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:delete


pumukitnewadmin_playlistpic_up:
    path: /{id}/up
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:up


pumukitnewadmin_playlistpic_down:
    path: /{id}/down
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:down


pumukitnewadmin_playlistpic_list:
    path: /{id}/list
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:list


pumukitnewadmin_playlistpic_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:show


pumukitnewadmin_playlistpic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:upload

pumukitnewadmin_playlistpic_picstoaddlist:
    path: /{id}/picstoaddlist
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:picstoaddlist

pumukitnewadmin_playlistpic_banner:
    path: /{id}/banner
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistPic:banner