pumukitnewadmin_seriespic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:index
        _sylius:
            filterable: true

pumukitnewadmin_seriespic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:create
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_seriespic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:update

pumukitnewadmin_seriespic_batch_delete:
    path: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:batchDelete
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_seriespic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:delete


pumukitnewadmin_seriespic_up:
    path: /{id}/up
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:up


pumukitnewadmin_seriespic_down:
    path: /{id}/down
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:down


pumukitnewadmin_seriespic_list:
    path: /{id}/list
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:list


pumukitnewadmin_seriespic_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:show


pumukitnewadmin_seriespic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:upload

pumukitnewadmin_seriespic_picstoaddlist:
    path: /{id}/picstoaddlist
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:picstoaddlist

pumukitnewadmin_seriespic_banner:
    path: /{id}/banner
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesPic:banner
