pumukitnewadmin_series_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Series:index
        _sylius:
            filterable: true

pumukitnewadmin_series_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Series:search

pumukitnewadmin_series_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:create
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_series_clone:
    path: /clone/{id}
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:clone

pumukitnewadmin_series_links:
    path: /{id}/links
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Series:links

pumukitnewadmin_series_update:
    path: /{id}/update
    methods: [GET, POST, DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Series:update

pumukitnewadmin_series_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Series:batchDelete
        _sylius:
            redirect: pumukitnewadmin_series_list

pumukitnewadmin_series_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Series:delete
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_series_generate_magic_url:
    path: /{id}/generatemagic
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:generateMagicUrl

pumukitnewadmin_series_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:copy
        _sylius:
            redirect: pumukitnewadmin_series_index

pumukitnewadmin_series_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Series:show

pumukitnewadmin_series_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:list

pumukitnewadmin_series_invert_announce:
    path: /invertannounce
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:invertAnnounce

pumukitnewadmin_series_changepub:
    path: /changepub
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Series:changePub

pumukitnewadmin_series_updatepub:
    path: /updatepub
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:updatePub

pumukitnewadmin_series_updatebroadcast:
    path: /{id}/updatebroadcast
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Series:updateBroadcast

pumukitnewadmin_series_listproperties:
    path: /{id}/listproperties
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Series:listProperties
