pumukitnewadmin_tag_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:index

pumukitnewadmin_tag_children:
    path: /{id}/children
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:children

pumukitnewadmin_tag_create:
    path: /create/parent/{parent}
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:create

pumukitnewadmin_tag_update:
    path: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:update

pumukitnewadmin_tag_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:delete

pumukitnewadmin_tag_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:list

pumukitnewadmin_tag_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Tag:batchDelete
