pumukitnewadmin_userclearance_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.userclearance:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_userclearance_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.userclearance:createAction
        _sylius:
            redirect: pumukitnewadmin_userclearance_index

pumukitnewadmin_userclearance_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.userclearance:updateAction
        _sylius:
            redirect: pumukitnewadmin_userclearance_index

pumukitnewadmin_userclearance_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.userclearance:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_userclearance_index

pumukitnewadmin_userclearance_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.userclearance:deleteAction
        _sylius:
            redirect: pumukitnewadmin_userclearance_index

pumukitnewadmin_userclearance_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.userclearance:listAction