pumukitwizard_js:
    pattern: /admin/wizard/pumukit2_wizard.js
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitWizardBundle::pumukit2_wizard.js.twig'
        _format: js

pumukitwizard_default:
    resource: @PumukitWizardBundle/Resources/config/routes/default.yml
    prefix: /admin/wizard

pumukitwizard_simple:
    resource: @PumukitWizardBundle/Resources/config/routes/simple.yml
    prefix: /admin/simplewizard
