pumukitwizard_default_index:
    path: /
    methods: [GET]
    defaults:
        _controller: PumukitWizardBundle:Default:series

pumukitwizard_default_license:
    path: /license
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:license

pumukitwizard_default_series:
    path: /series
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:series

pumukitwizard_default_type:
    path: /type/{id}
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:type

pumukitwizard_default_option:
    path: /option
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:option

pumukitwizard_default_multimediaobject:
    path: /multimediaobject
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:multimediaobject

pumukitwizard_default_track:
    path: /track
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:track

pumukitwizard_default_upload:
    path: /upload
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:upload

pumukitwizard_default_end:
    path: /end
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:end

pumukitwizard_default_error:
    path: /error
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Default:error
