pumukitwizard_simple_index:
    path: /index/{id}
    methods: [GET]
    defaults:
        _controller: PumukitWizardBundle:Simple:index

pumukitwizard_simple_upload:
    path: /upload/{id}
    methods: [POST]
    defaults:
        _controller: PumukitWizardBundle:Simple:upload

pumukitwizard_simple_embedindex:
    path: /embedindex
    methods: [GET]
    defaults:
        _controller: PumukitWizardBundle:Simple:embedindex

pumukitwizard_simple_embedupload:
    path: /embedupload
    methods: [GET, POST]
    defaults:
        _controller: PumukitWizardBundle:Simple:embedupload
