# Sylius resource
sylius_resource:
    resources:
        pumukitadmin.user:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:User
            classes:
                model: Pumukit\SchemaBundle\Document\User