# Sylius resource
sylius_resource:
    resources:
        pumukitadmin.user:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:User
            classes:
                model: Pumukit\SchemaBundle\Document\User
                controller: Pumukit\AdminBundle\Controller\AdminController
        pumukitadmin.direct:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Direct
            classes:
                model: Pumukit\DirectBundle\Document\Direct
                controller: Pumukit\AdminBundle\Controller\AdminController
        pumukitadmin.event:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Event
            classes:
                model: Pumukit\DirectBundle\Document\Event
                controller: Pumukit\AdminBundle\Controller\CalendarAdminController
        pumukitadmin.role:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Role
            classes:
                model: Pumukit\SchemaBundle\Document\Role
                controller: Pumukit\AdminBundle\Controller\SortableAdminController
        pumukitadmin.broadcast:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Broadcast
            classes:
                model: Pumukit\SchemaBundle\Document\Broadcast
                controller: Pumukit\AdminBundle\Controller\BroadcastAdminController
        pumukitadmin.series:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Series
            classes:
                model: Pumukit\SchemaBundle\Document\Series
                controller: Pumukit\AdminBundle\Controller\AdminController