# Sylius resource
sylius_resource:
    resources:
        pumukitadmin.user:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:User
            classes:
                model: Pumukit\SchemaBundle\Document\User
        pumukitadmin.direct:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Direct
            classes:
                model: Pumukit\DirectBundle\Document\Direct
        pumukitadmin.event:
            driver: doctrine/mongodb-odm
            templates: PumukitAdminBundle:Event
            classes:
                model: Pumukit\DirectBundle\Document\Event