pumukitadmin_event_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.event:indexAction

pumukitadmin_event_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.event:createAction
        _sylius:
            reevent: pumukitadmin_event_show

pumukitadmin_event_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.event:updateAction
        _sylius:
            reevent: pumukitadmin_event_show

pumukitadmin_event_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.event:deleteAction
        _sylius:
            reevent: pumukitadmin_event_index

pumukitadmin_event_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.event:showAction