pumukitadmin_fos_user:
    resource: @PumukitAdminBundle/Resources/config/fos_user.yml

pumukitadmin_user:
    resource: @PumukitAdminBundle/Resources/config/user.yml
    prefix: /users

pumukitadmin_direct:
    resource: @PumukitAdminBundle/Resources/config/direct.yml
    prefix: /direct
