pumukitadmin_fos_user:
    resource: @PumukitAdminBundle/Resources/config/fos_user.yml

pumukit_direct:
    resource: "@PumukitAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

pumukitadmin_user:
    resource: @PumukitAdminBundle/Resources/config/user.yml
    prefix: /admin/users

pumukitadmin_direct:
    resource: @PumukitAdminBundle/Resources/config/direct.yml
    prefix: /admin/direct

pumukitadmin_event:
    resource: @PumukitAdminBundle/Resources/config/event.yml
    prefix: /admin/event

pumukitadmin_role:
    resource: @PumukitAdminBundle/Resources/config/role.yml
    prefix: /admin/role