pumukitadmin_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.user:indexAction

pumukitadmin_user_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: pumukitadmin.controller.user:createAction
        _sylius:
            redirect: pumukitadmin_user_show

pumukitadmin_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitadmin.controller.user:updateAction
        _sylius:
            redirect: pumukitadmin_user_show

pumukitadmin_user_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitadmin.controller.user:deleteAction
        _sylius:
            redirect: pumukitadmin_user_index

pumukitadmin_user_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: pumukitadmin.controller.user:showAction
