name: Code validation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        runs: |
               docker-compose -f docker-compose.yml build --build-arg APP_ENV=dev
               docker-compose -f docker-compose.yml up -d h2-proxy

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Lints
        run:  docker-compose -f docker-compose.yml exec php composer lints

      - name: PHPCSFixer
        run:  docker-compose -f docker-compose.yml exec php composer php-cs-fixer

      - name: PHPStan
        run:  docker-compose -f docker-compose.yml exec php composer phpstan

      - name: Test
        run: docker-compose -f docker-compose.yml exec php composer tests

      - name: Fixtures
        run: docker-compose -f docker-compose.yml exec php bin/console pumukit:init:repo all --force
