name: Code validation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run:  |
              docker-compose -f docker-compose.yml build --build-arg APP_ENV=dev
              docker-compose -f docker-compose.yml up -d h2-proxy

      - name: Validate composer.json and composer.lock
        run:  composer validate

      - name: Lints
        run:  docker-compose -f docker-compose.yml exec -T php composer lints

      - name: PHPCSFixer
        run:  docker-compose -f docker-compose.yml exec -T php composer php-cs-fixer

      - name: PHPStan
        run:  docker-compose -f docker-compose.yml exec -T php composer phpstan

      - name: Test
        run:  docker-compose -f docker-compose.yml exec -T php composer tests

      - name: Fixtures
        run:  docker-compose -f docker-compose.yml exec -T php bin/console pumukit:init:repo all --force
