sylius_resource:
    resources:
        pumukitnewadmin.person:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Person
            classes:
                model: Pumukit\SchemaBundle\Document\Person
                controller: Pumukit\NewAdminBundle\Controller\PersonController
        pumukitnewadmin.series:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Series
            classes:
                model: Pumukit\SchemaBundle\Document\Series
                controller: Pumukit\NewAdminBundle\Controller\SeriesController
        pumukitnewadmin.mmtemplate:
            driver: doctrine/mongodb-odm
            templates: PumukitnewadminBundle:MultimediaObjectTemplate
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectTemplateController
        pumukitnewadmin.mms:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:MultimediaObject
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController
        pumukitnewadmin.seriespic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\SchemaBundle\Document\Pic
                controller: Pumukit\NewAdminBundle\Controller\SeriesPicController
        pumukitnewadmin.mmspic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\SchemaBundle\Document\Pic
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController
