pumukit_js:
    pattern: /admin/pumukit2.js
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitNewAdminBundle::pumukit2.js.twig'
        _format: js

pumukit_css:
    pattern: /admin/pumukit2.css
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'PumukitNewAdminBundle::pumukit2.css.twig'
        _format: css

pumukitnewadmin_person:
    resource: @PumukitNewAdminBundle/Resources/config/routes/person.yml
    prefix: /admin/person

pumukitnewadmin_series:
    resource: @PumukitNewAdminBundle/Resources/config/routes/series.yml
    prefix: /admin/series

pumukitnewadmin_mmtemplate:
    resource: @PumukitNewAdminBundle/Resources/config/routes/mmtemplate.yml
    prefix: /admin/mmtemplate

pumukitnewadmin_mms:
    resource: @PumukitNewAdminBundle/Resources/config/routes/mms.yml
    prefix: /admin/mms

pumukitnewadmin_seriespic:
    resource: @PumukitNewAdminBundle/Resources/config/routes/seriespic.yml
    prefix: /admin/seriespic

pumukitnewadmin_mmspic:
    resource: @PumukitNewAdminBundle/Resources/config/routes/mmspic.yml
    prefix: /admin/mmspic

pumukitnewadmin_tag:
    resource: @PumukitNewAdminBundle/Resources/config/routes/tag.yml
    prefix: /admin/tag